{"name": "test_get_routines_list", "status": "broken", "statusDetails": {"message": "TypeError: 'dict' object is not callable", "trace": "login_token = {'accessToken': 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MiIsImV4cCI6MTcxNzk0NjMxOCwicm9sZXMiOlsiVVNFUiJdLCJlbWFpbCI6InNoaW5h...GciOiJIUzI1NiJ9.eyJzdWIiOiI1MiIsImV4cCI6MTcyMDUzNzcxOH0.MG8sKakycwo6GPgT680xzvvNXvlvAyF4e8TAd_FStM4', 'type': 'Bearer'}\n\n    @allure.feature('Routine')\n    @allure.story('Get routines list')\n    def test_get_routines_list(login_token):\n        headers = {\n>           \"Authorization\": f\"Bearer {login_token()['accessToken']}\",\n            \"Accept\": \"*/*\",\n        }\nE       TypeError: 'dict' object is not callable\n\ntests/test_routine.py:60: TypeError"}, "start": 1717945718138, "stop": 1717945718138, "uuid": "267753a8-8eb6-460c-b3f0-4777a75cb50e", "historyId": "3d1249ff2399ce9cc7b0580766314fa7", "testCaseId": "3d1249ff2399ce9cc7b0580766314fa7", "fullName": "tests.test_routine#test_get_routines_list", "labels": [{"name": "story", "value": "Get routines list"}, {"name": "feature", "value": "Routine"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_routine"}, {"name": "host", "value": "Air-makbuk.Dlink"}, {"name": "thread", "value": "50615-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_routine"}]}