{"name": "test_delete_routine", "status": "broken", "statusDetails": {"message": "TypeError: 'int' object is not callable", "trace": "login_token = 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MiIsImV4cCI6MTcxNzk0NzkzMSwicm9sZXMiOlsiVVNFUiJdLCJlbWFpbCI6InNoaW5hODIxNEBmdGhjYXBpdGFsLmNvbSJ9.p2AhGHEjbx7sOT5ePNjdGbb1eEQk6lAfflGNvRX-KZg'\ncreate_routine = 491\n\n    @allure.feature('Routine')\n    @allure.story('Delete routine')\n    def test_delete_routine(login_token, create_routine):\n        with allure.step('Create Routine'):\n            headers = {\n                \"Authorization\": f\"Bearer {login_token}\",\n                \"Accept\": \"*/*\",\n            }\n>           new_routine = create_routine()\nE           TypeError: 'int' object is not callable\n\ntests/test_routine.py:128: TypeError"}, "steps": [{"name": "Create Routine", "status": "broken", "statusDetails": {"message": "TypeError: 'int' object is not callable\n", "trace": "  File \"/Users/alya/shit/tmm/tests/test_routine.py\", line 128, in test_delete_routine\n    new_routine = create_routine()\n                  ^^^^^^^^^^^^^^^^\n"}, "start": 1717947332406, "stop": 1717947332406}], "start": 1717947332406, "stop": 1717947332406, "uuid": "20d8b00d-6268-46e1-99b0-3725c5be983d", "historyId": "47d1634a650334f498c847785dcdeb1f", "testCaseId": "47d1634a650334f498c847785dcdeb1f", "fullName": "tests.test_routine#test_delete_routine", "labels": [{"name": "feature", "value": "Routine"}, {"name": "story", "value": "Delete routine"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_routine"}, {"name": "host", "value": "Air-makbuk.Dlink"}, {"name": "thread", "value": "51159-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_routine"}]}